### ISSUE TITLE
Port to 1.20.1?

### ISSUE THREAD

**Issue by LordFirecat** [eclipseisoffline/bookcopy#1]
I play on a roleplay server with my family, and we are on 1.20.1. Would you be able to port to 1.20.1?

**Comment by eclipseisoffline** [comment]
Hi, I've considered making a 1.20.1 port earlier but I've been busy. I'll try to get one working today.

**Comment by eclipseisoffline** [comment]
A 1.20.1 port is now available on Modrinth
