### ISSUE TITLE
1.20.5 version is incompatibel with 1.20.6

### ISSUE THREAD

**Issue by J4PC** [eclipseisoffline/bookcopy#2]
**Describe the bug**
1.20.5 version is incompatibel with 1.20.6

**To Reproduce**
1. Start Minecraft 1.20.6 with the Mod

**Expected behavior**
Because the only meaningful change between the two versions is a bug fix for llama inventories, the mod should work for 1.20.6.

**Screenshots**
![image](https://github.com/eclipseisoffline/bookcopy/assets/97805057/9579276d-9db7-42a0-87ce-f8b033898511)

**Minecraft setup (please complete the following information):**
 - Minecraft version: 1.20.6
 - Fabric loader: .15.10
 - Book Copy version: Book Copy 0.1.1-1.20.5
 - fabric-api-0.97.8+1.20.6

**Comment by sauron65** [comment]
Now 1.21.8 doesn't work even though 1.21.8 shouldn't've made any changes to books.
